<a href="https://colab.research.google.com/github/meenakshireddy2903-cpu/DataAnalysis_Tasks/blob/main/NUMPY_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY TASK

**PART-1**

In [12]:
#importing library to perform mathematical operations
import numpy as np
arr2 = [1,2,3,4,5,6,7,8,9]
arr = [1,2,5,4,8,7,9,]

In [13]:
#CREATING AND RESHAPING ARRAYS
#1CREATE ARRAYS
#1D ARRAY OF 10 EQUALLY SPACED VALUES BTW 0,50
np.linspace(0,50,10)
#A 2D ARRAY OF SHAPE(3X3) containing random integers btw 5 and 20
arr2 = np.random.randint(5, 20, 9).reshape(3, 3)
print(arr2)

[[17 11  5]
 [16  9 11]
 [ 9 13  8]]


In [14]:
#ARRAY DIMENSIONS
#PRINT THE DIMENSIONS OF BOTH ARRAYS
arr2.ndim
#PRINT THE SHAPE OF BOTH ARRAY
arr2.shape

(3, 3)

In [15]:
#PART 2
#INDEXING
#FOR THE 2D ARRAY CREATED IN PART 1, PRINT THE ELEMENT PRESENT AT THE 2ND ROW AND 3RD COLUMN
arr2[1,2]
#EXTRACT THE FIRST TWO ROWS AND THE LAST TWO COL OF ARRAY
arr2[0:2,1:]


array([[11,  5],
       [ 9, 11]])

In [16]:
#SLICING
#SLICE THE FIRST  4 ELEMENTS FROM THE FLATTENED 1D ARRAY
arr[0:4]
#reversing the array
arr[::-1]

[9, 7, 8, 4, 5, 2, 1]

In [17]:
import numpy as np
#PART -3
#ARRAY ARITHEMATIC:
arr = np.array([1,2,3,4,5,6,7,8,9]) # Redefined arr here for Part 3
#CREATE ANOTHR 1D ARRAY OF 9 INTEGERS BTW 1 TO 9 to match the length of arr
arr3 = np.arange(1,10) # Changed from 1,11 to 1,10
#PERFORM THE FOLLOWING ELEMENT-WISE OPERATIONS BTW THE 1D ARRAYS CREATED IN PART 1 AND PART 3
#ADDITION
print("Addition:", arr + arr3)
#MULTIPLICATION
print("Multiplication:", arr * arr3)
#SUBTRACTION
print("Subtraction:", arr3 - 5)

Addition: [ 2  4  6  8 10 12 14 16 18]
Multiplication: [ 1  4  9 16 25 36 49 64 81]
Subtraction: [-4 -3 -2 -1  0  1  2  3  4]


In [18]:
#CREATE A 1D ARRAY OF 5 RANDOM VALUES BETWEEN 0 AND 1
arr = np.random.rand(5)
arr


array([0.78263471, 0.67163566, 0.56230235, 0.81247045, 0.02200648])

In [19]:
#CREATE ANOTHER 1D ARRAY OF 5 RANDOM VALUES BETWEEN -1 AND 1
arr = np.random.randint(-1,1,5)
arr

array([ 0, -1, -1,  0,  0])

In [20]:
n = int(input("Enter an integer for n: "))

# Generate an n x n array of random integers between 1 and 100
array = np.random.randint(1, 101, size=(n, n))
print(array)
print(array.shape)

Enter an integer for n: 7
[[24 93 35 11 52  1 99]
 [79 29 25 76 31 55 38]
 [80 40 66 61 21 97 80]
 [42 13  1 50 11  6  4]
 [16 38 72 41 78 50 44]
 [72 73 20 71 27  6 92]
 [62 17 64 44 76 56 71]]
(7, 7)


In [21]:
#Find the sum of all the elements in the array and print the result.
np.sum(array)

np.int64(2310)